In [1]:
league = 'USHL'
season = '2021-22'

In [16]:
from pucknight import pn_queries, ep_soup, pg_db
import pandas as pd
stand = pn_queries.league_standings(league,season)
stats = pn_queries.league_scoring(league, season)
goalies = pn_queries.league_goalies(league, season)

In [5]:
stand[['div_pos','team','points','ppg','wins','losses','goal_diff','division']]

,div_pos,team,points,ppg,wins,losses,goal_diff,division
0,1,Tri-City Storm,57,1.68,28,5,74,Western
1,1,Muskegon Lumberjacks,49,1.32,22,10,17,Eastern
2,2,Chicago Steel,48,1.37,21,8,25,Eastern
3,2,Sioux City Musketeers,44,1.29,20,10,23,Western
4,3,Dubuque Fighting Saints,43,1.26,19,10,31,Eastern
5,3,Omaha Lancers,43,1.26,19,10,7,Western
6,4,Lincoln Stars,39,1.18,18,12,4,Western
7,4,Madison Capitols,38,1.03,18,17,-4,Eastern
8,5,Waterloo Black Hawks,36,1.03,17,16,-9,Western
9,5,Youngstown Phantoms,35,1.06,15,13,-2,Eastern
10,6,Green Bay Gamblers,35,1.03,16,15,-14,Eastern
11,6,Fargo Force,32,0.91,14,17,-20,Western
12,7,Cedar Rapids RoughRiders,30,0.91,14,17,-21,Eastern
13,7,Des Moines Buccaneers,27,0.77,12,20,-21,Western
14,8,Sioux Falls Stampede,25,0.71,11,21,-58,Western
15,8,USNTDP Juniors,23,0.77,10,17,-32,Eastern

In [13]:
home = stand.iloc[0].team
away = stand.iloc[2].team
matchup_plrs = stats[(stats['team']==home) | (stats['team']==away)]
matchup_gs = goalies[(goalies['team']==home) | (goalies['team']==away)]

In [7]:
stand[(stand['team']==home) | (stand['team']==away)]\
    [['team','gp','points','ppg','wins','goals','goals_against','division','div_pos']].T

                            0              2
team           Tri-City Storm  Chicago Steel
gp                         34             35
points                     57             48
ppg                      1.68           1.37
wins                       28             21
goals                     137            143
goals_against              63            118
division              Western        Eastern
div_pos                     1              2

In [21]:
matchup_plrs.sort_values('tp', ascending=False)\
    [['team','playername','gp','tp','g','a','pim','plus_minus','ppg'
      ,'age_curr','place_of_birth','height','weight','playerid']]\
.iloc[:25]

,team,playername,gp,tp,g,a,pim,plus_minus,ppg,age_curr,place_of_birth,height,weight,playerid
1,Chicago Steel,Jackson Blake,35,53,18,35,8,14.0,1.51,18.3,"Eden Prairie, MN, USA",5'10,148,574744
3,Tri-City Storm,Jeremy Wilmer,34,47,14,33,36,20.0,1.38,18.3,"Rockville Centre, NY, USA",5'7,141,461967
7,Tri-City Storm,Cole O'Hara,34,41,17,24,16,15.0,1.21,19.4,"Richmond Hill, ON, CAN",5'11,174,201938
8,Tri-City Storm,Mitchell Miller,34,41,14,27,51,21.0,1.21,19.9,"Sylvania, OH, USA",5'11,194,316129
11,Chicago Steel,Adam Fantilli,31,40,23,17,71,9.0,1.29,17.2,"Nobleton, ON, CAN",6'2,190,603785
12,Chicago Steel,Joe Miller,35,39,14,25,12,10.0,1.11,19.3,"Minneapolis, MN, USA",5'9,150,201857
13,Chicago Steel,Sam Lipkin,32,39,18,21,8,9.0,1.22,18.9,"Lafayette Hill, PA, USA",6'3,196,478367
18,Tri-City Storm,Ilya Nikolayev,31,35,11,24,33,19.0,1.13,20.4,"Yaroslavl, RUS",5'11,183,514152
35,Chicago Steel,Jake Livanavage,35,28,2,26,28,7.0,0.80,17.6,"Gilbert, AZ, USA",5'10,154,571946
36,Tri-City Storm,Lleyton Roed,32,28,15,13,27,10.0,0.88,19.3,"White Bear Lake, MN, USA",6'0,179,551465
38,Chicago Steel,Jayden Perron,35,28,10,18,6,8.0,0.80,16.9,"Winnipeg, MB, CAN",5'8,141,648248
44,Tri-City Storm,Gavin Brindley,28,25,13,12,10,5.0,0.89,17.2,"Estero, FL, USA",5'8,152,538006
49,Chicago Steel,Lukas Gustafsson,32,24,7,17,26,4.0,0.75,18.9,"Alpharetta, GA, USA",5'10,181,551973
51,Chicago Steel,Jack Harvey,33,24,12,12,8,-3.0,0.73,18.7,"Stacy, MN, USA",5'10,165,512111
62,Tri-City Storm,Tanner Adams,34,22,9,13,4,15.0,0.65,16.3,"Northport, NY, USA",5'11,170,599375
81,Chicago Steel,Andon Cerbone,35,18,5,13,32,-2.0,0.51,17.7,"Stanford, CT, USA",5'9,150,526237
83,Tri-City Storm,Vinny Borgesi,31,18,2,16,12,21.0,0.58,17.8,"Philadelphia, PA, USA",5'8,165,478377
94,Tri-City Storm,Victor Czerneckianair,22,17,4,13,6,11.0,0.77,19.8,"Southington, CT, USA",5'11,174,417303
100,Tri-City Storm,Andrew Strathmann,34,16,1,15,55,11.0,0.47,16.8,"Beach Park, IL, USA",5'11,174,637628
107,Tri-City Storm,Graham Gamache,34,15,5,10,0,8.0,0.44,19.5,"Edmonton, AB, CAN",5'11,172,476536
123,Tri-City Storm,Kieran Cebrian,34,14,7,7,42,12.0,0.41,18.7,"Denver, CO, USA",6'2,194,481259
133,Chicago Steel,Nicholas Moldenhauer,19,14,7,7,0,5.0,0.74,17.5,"Mississauga, ON, CAN",5'11,170,535872
151,Tri-City Storm,Christian Fitzgerald,15,12,6,6,6,5.0,0.80,19.5,"Coquitlam, BC, CAN",6'0,174,290350
152,Tri-City Storm,Dane Dowiak,32,12,6,6,40,10.0,0.38,19.7,"Wexford, PA, USA",5'10,172,481515
158,Chicago Steel,Luca Fantilli,34,12,1,11,8,-2.0,0.35,18.9,"Kleinburg, ON, CAN",6'0,159,582775

In [14]:
matchup_gs.sort_values('gp', ascending=False)\
    [['team','playername','gp','gaa','sv_prc','age_curr','place_of_birth','height','weight','playerid']]

,team,playername,gp,gaa,sv_prc,age_curr,place_of_birth,height,weight,playerid
60,Tri-City Storm,Arseni Sergeyev,26,1.55,0.936,18.8,"Yaroslavl, RUS",6'3,192,592505
35,Chicago Steel,Gibson Homer,19,3.45,0.889,17.8,"Grand Rapids, MI, USA",6'5,209,511952
45,Chicago Steel,Nick Haas,11,3.15,0.895,19.9,"Williamsville, NY, USA",6'5,194,440460
57,Tri-City Storm,Chase Clark,7,2.51,0.915,19.5,"Williamsville, NY, USA",6'6,218,485634
53,Chicago Steel,Christian Manz,6,2.80,0.909,17.8,"Blaine, MN, USA",6'0,176,616273
30,Tri-City Storm,Sebastian Wraneschitz,2,2.50,0.886,19.6,"Wien, AUT",5'11,181,470070
61,Tri-City Storm,Michael Sochan Jr.,1,0.00,1.000,19.2,"CA, USA",6'1,179,417336
5,Chicago Steel,Jack Stark,0,0.00,0.000,18.3,"Chaska, MN, USA",5'9,146,574742

In [17]:
### BUILD DFs
plr_info_df = pd.DataFrame()
for p in list(matchup_plrs.playerid):
    plr_row = pn_queries.player_info(p)
    plr_info_df = pd.concat([plr_info_df,plr_row])
plr_info_df = plr_info_df.merge(stats[['playerid','team','gp']], on='playerid',
                              suffixes=['','_cur'])

plr_car_df = pd.DataFrame()
for p in list(matchup_plrs.playerid):
    plr_row = pn_queries.player_career(p)
    plr_car_df = pd.concat([plr_car_df,plr_row])
plr_car_df = plr_car_df.merge(stats[['playerid','team','gp']], on='playerid',
                              suffixes=['','_cur'])

plr_awards = pd.DataFrame()
for p in list(matchup_plrs.playerid):
    plr_row = pn_queries.award_winners(p)
    plr_awards = pd.concat([plr_awards,plr_row])
plr_awards = plr_car_df.merge(stats[['playerid','team']], on='playerid',
                              suffixes=['','_cur'])

In [19]:
plr_info_df[plr_info_df.overall_pick.notnull()].merge(stats, on='playerid',
                                                      suffixes=['','_stats'])\
    .groupby(['team','playername']).agg({'draft_year':'max','overall_pick':'max',
                                       'draft_team':'max','position':'max'})

                               draft_year  overall_pick           draft_team  \
team           playername
Chicago Steel  Jackson Blake         2021           109  Carolina Hurricanes
               Joe Miller            2020           180  Toronto Maple Leafs
               Sam Lipkin            2021           223      Arizona Coyotes
Tri-City Storm Ilya Nikolayev        2019            88       Calgary Flames
               Mitchell Miller       2020           111      Arizona Coyotes
               Nate Benoit           2021           182       Minnesota Wild

                               position
team           playername
Chicago Steel  Jackson Blake          F
               Joe Miller             F
               Sam Lipkin            LW
Tri-City Storm Ilya Nikolayev         C
               Mitchell Miller        D
               Nate Benoit            D

In [20]:
plr_car_df[(plr_car_df['season']=='2022-23') & (plr_car_df['league']=='NCAA')]\
    .merge(stats, on='playerid', suffixes=['','_stats'])\
        .groupby(['team','season','team_stats','playername'])\
            .agg({'place_of_birth':'max','gp_stats':'max','tp':'max'})

                                                                                            place_of_birth  \
team                            season  team_stats     playername
Bemidji State Univ.             2022-23 Tri-City Storm Lleyton Roed               White Bear Lake, MN, USA
Boston College                  2022-23 Chicago Steel  Lukas Gustafsson                Alpharetta, GA, USA
Boston Univ.                    2022-23 Chicago Steel  Jack Harvey                          Stacy, MN, USA
Minnesota State Univ. (Mankato) 2022-23 Tri-City Storm Christian Fitzgerald             Coquitlam, BC, CAN
                                                       Graham Gamache                    Edmonton, AB, CAN
                                                       Mason Wheeler          Inver Grove Heights, MN, USA
Northeastern Univ.              2022-23 Tri-City Storm Vinny Borgesi                 Philadelphia, PA, USA
Penn State Univ.                2022-23 Tri-City Storm Dane Dowiak                        Wexford, PA, USA
Providence College              2022-23 Chicago Steel  Anthony Dowd          Point Pleasant Beach, NJ, USA
                                                       Austen May                       Woodhaven, MI, USA
Quinnipiac Univ.                2022-23 Chicago Steel  Sam Lipkin                  Lafayette Hill, PA, USA
Univ. of Denver                 2022-23 Tri-City Storm Kieran Cebrian                      Denver, CO, USA
Univ. of Michigan               2022-23 Chicago Steel  Adam Fantilli                     Nobleton, ON, CAN
                                                       Andon Cerbone                     Stanford, CT, USA
                                                       Luca Fantilli                    Kleinburg, ON, CAN
Univ. of Minnesota              2022-23 Chicago Steel  Joe Miller                     Minneapolis, MN, USA
Univ. of Minnesota-Duluth       2022-23 Tri-City Storm Aiden Dubinsky               Highland Park, IL, USA
Univ. of North Dakota           2022-23 Chicago Steel  Jackson Blake                 Eden Prairie, MN, USA
                                        Tri-City Storm Nate Benoit                            Bow, NH, USA
Univ. of Vermont                2022-23 Tri-City Storm Mario Gasparini                  Lakeville, MN, USA
Univ. of Wisconsin              2022-23 Chicago Steel  Luke Levandowski                 Rosemount, MN, USA
                                                       Shawn Ramsey                   Mississauga, ON, CAN

                                                                             gp_stats  \
team                            season  team_stats     playername
Bemidji State Univ.             2022-23 Tri-City Storm Lleyton Roed                32
Boston College                  2022-23 Chicago Steel  Lukas Gustafsson            32
Boston Univ.                    2022-23 Chicago Steel  Jack Harvey                 33
Minnesota State Univ. (Mankato) 2022-23 Tri-City Storm Christian Fitzgerald        15
                                                       Graham Gamache              34
                                                       Mason Wheeler               27
Northeastern Univ.              2022-23 Tri-City Storm Vinny Borgesi               31
Penn State Univ.                2022-23 Tri-City Storm Dane Dowiak                 32
Providence College              2022-23 Chicago Steel  Anthony Dowd                34
                                                       Austen May                  35
Quinnipiac Univ.                2022-23 Chicago Steel  Sam Lipkin                  32
Univ. of Denver                 2022-23 Tri-City Storm Kieran Cebrian              34
Univ. of Michigan               2022-23 Chicago Steel  Adam Fantilli               31
                                                       Andon Cerbone               35
                                                       Luca Fantilli               34
Univ. of Minnesota              2022-23 Chicago Steel  Joe Miller                  35
Univ. of Minnesota-Duluth       2022-23 Tri-City Storm Aiden Dubinsky              33
Univ. of North Dakota           2022-23 Chicago Steel  Jackson Blake               35
                                        Tri-City Storm Nate Benoit                 34
Univ. of Vermont                2022-23 Tri-City Storm Mario Gasparini              4
Univ. of Wisconsin              2022-23 Chicago Steel  Luke Levandowski            19
                                                       Shawn Ramsey                19

                                                                             tp
team                            season  team_stats     playername
Bemidji State Univ.             2022-23 Tri-City Storm Lleyton Roed          28
Boston College                  2022-23 Chicago Steel  Lukas Gustafsson      24
Boston Univ.                    2022-23 Chicago Steel  Jack Harvey           24
Minnesota State Univ. (Mankato) 2022-23 Tri-City Storm Christian Fitzgerald  12
                                                       Graham Gamache        15
                                                       Mason Wheeler          4
Northeastern Univ.              2022-23 Tri-City Storm Vinny Borgesi         18
Penn State Univ.                2022-23 Tri-City Storm Dane Dowiak           12
Providence College              2022-23 Chicago Steel  Anthony Dowd          10
                                                       Austen May             6
Quinnipiac Univ.                2022-23 Chicago Steel  Sam Lipkin            39
Univ. of Denver                 2022-23 Tri-City Storm Kieran Cebrian        14
Univ. of Michigan               2022-23 Chicago Steel  Adam Fantilli         40
                                                       Andon Cerbone         18
                                                       Luca Fantilli         12
Univ. of Minnesota              2022-23 Chicago Steel  Joe Miller            39
Univ. of Minnesota-Duluth       2022-23 Tri-City Storm Aiden Dubinsky        10
Univ. of North Dakota           2022-23 Chicago Steel  Jackson Blake         53
                                        Tri-City Storm Nate Benoit            6
Univ. of Vermont                2022-23 Tri-City Storm Mario Gasparini        0
Univ. of Wisconsin              2022-23 Chicago Steel  Luke Levandowski       9
                                                       Shawn Ramsey           0

In [22]:
pid = '461967'

In [23]:
plr_info_df[plr_info_df['playerid']==pid].T

                                        1
playername                  Jeremy Wilmer
height                                5'7
weight                                141
shoots_catches                          L
position                                C
draft_year                           None
draft_round                          None
overall_pick                         None
draft_team                           None
nation                                USA
dob                            2003-08-16
place_of_birth  Rockville Centre, NY, USA
youth_team                              -
playerid                           461967
team                       Tri-City Storm
gp                                     34

In [29]:
plr_car_df[plr_car_df['playerid']==pid]\
    [['season','league','team','gp','g_gaa','tp_svpct','postseason','post_gp','szn_age']]

,season,league,team,gp,g_gaa,tp_svpct,postseason,post_gp,szn_age
15,2014-15,WSI U12,East Coast Selects Q U12,9,3.0,6.0,None,0,11.33
16,2015-16,QC Int PW,Long Island Stars,2,0.0,1.0,None,0,12.33
17,2016-17,AYHL 13U,Long Island Gulls 13U AAA,23,35.0,73.0,Semifinal loss,0,13.33
18,2017-18,WSI U15,East Coast Selects Q U15,6,6.0,9.0,None,0,14.33
19,2017-18,USHS-Prep,Portledge School,17,18.0,48.0,None,0,14.33
20,2018-19,USHS-Prep,Portledge School,11,12.0,31.0,None,0,15.33
21,2018-19,USA-S15,Team Grey,4,1.0,6.0,None,0,15.33
22,2019-20,USDP,U.S. National U17 Team,45,12.0,33.0,None,0,16.33
23,2019-20,USHL,USNTDP Juniors,27,5.0,14.0,Playoffs Cancelled,0,16.33
24,2019-20,WHC-17,USA U17,6,2.0,7.0,Final loss,0,16.33
25,2020-21,USDP,U.S. National U18 Team,37,11.0,36.0,None,0,17.33
26,2020-21,USDP,U.S. National U17 Team,2,0.0,1.0,None,0,17.33
27,2020-21,USHL,USNTDP Juniors,22,3.0,16.0,Did not make playoffs,0,17.33
28,2021-22,NCAA,Boston Univ.,0,0.0,0.0,0,0,18.33
29,None,None,None,21,34.0,73.0,None,0,NaN
30,None,None,None,22,27.0,62.0,None,0,NaN
31,None,None,None,25,23.0,61.0,None,0,NaN
32,None,None,None,9,5.0,14.0,None,0,NaN